$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$Repo='nanotech-solutions-norway/Domeneshop---MCP-'; $ExpectedBranch='main'; $StateRoot='C:\ProgramData\NanoTech\DomeneshopMcp\pilot-state'; $SecretFile=Join-Path $StateRoot 'approval-signing-secret.txt'; $ResultFile=Join-Path $StateRoot 'audit\d-r3-txt-restore-result.json'
Write-Host ''; Write-Host '============================================================'; Write-Host 'DOMENESHOP MCP — D-R3 AUTHORIZED TXT RESTORE'; Write-Host 'Office PC / isolated non-production target only'; Write-Host '============================================================'
if(-not(Test-Path '.git')){throw 'Run this script from the Domeneshop MCP repository root.'}
$Remote=(git remote get-url origin).Trim(); if($LASTEXITCODE-ne 0-or $Remote-notmatch'Domeneshop---MCP-'){throw 'Current repository is not the Domeneshop MCP checkout.'}
Write-Host ''; Write-Host '=== 1. Synchronize accepted main ==='; $WorkingTreeStatus=@(git status --porcelain); if($WorkingTreeStatus.Count-ne 0){throw 'Repository working tree is not clean. Stop before live execution.'}; git fetch origin main; git checkout $ExpectedBranch; git pull --ff-only origin main; if($LASTEXITCODE-ne 0){throw 'Unable to synchronize accepted main.'}
Write-Host ''; Write-Host '=== 2. Verify GitHub identity ==='; gh auth status; if($LASTEXITCODE-ne 0){throw 'GitHub CLI is not authenticated.'}; $Operator=(gh api user --jq '.login').Trim(); if(-not $Operator){throw 'Unable to resolve operator identity from GitHub.'}; Write-Host "Operator identity: $Operator"
Write-Host ''; Write-Host '=== 3. Verify protected Office-PC state root ==='; if(-not(Test-Path $StateRoot)){throw 'Protected pilot state root is missing.'}; if(-not(Test-Path $SecretFile)){throw 'Approval signing secret is missing from protected pilot state.'}
Write-Host ''; Write-Host '=== 4. Resolve protected pilot inputs ==='; if(-not $env:DS_PILOT_DOMAIN_NAME){$env:DS_PILOT_DOMAIN_NAME=Read-Host 'Enter the registered isolated pilot domain name'}; if(-not $env:DS_AUTH_USER-or-not $env:DS_AUTH_VALUE){throw 'DS_AUTH_USER / DS_AUTH_VALUE are not loaded on this Office PC. Load them locally; do not paste credentials into ChatGPT.'}; $env:DS_PILOT_TXT_HOST='_mcp-validation'
Write-Host ''; Write-Host '=== 5. Load protected approval signing secret ==='; $env:APPROVAL_SIGNING_SECRET=[System.IO.File]::ReadAllText($SecretFile,[System.Text.Encoding]::UTF8).Trim(); if([System.Text.Encoding]::UTF8.GetByteCount($env:APPROVAL_SIGNING_SECRET)-lt 32){throw 'Local approval signing secret is invalid.'}
Write-Host ''; Write-Host '=== 6. Refresh isolated Python runtime ==='; $Venv=Join-Path(Get-Location)'.venv-d-r3-live-create'; if(-not(Test-Path $Venv)){python -m venv $Venv}; $Python=Join-Path $Venv 'Scripts\python.exe'; & $Python -m pip install --disable-pip-version-check -e '.'|Out-Host; if($LASTEXITCODE-ne 0){throw 'Failed to install accepted package.'}
Write-Host ''; Write-Host '=== 7. Arm exact one-shot RESTORE process ==='; $env:PILOT_STATE_ROOT=$StateRoot; $env:D_R3_OPERATOR=$Operator; $env:D_R3_RESTORE_AUTHORIZATION_PHRASE='AUTHORIZE_D_R3_TXT_RESTORE'; $env:WRITE_TOOLS_ENABLED='true'; $env:DRY_RUN_DEFAULT='false'; $env:REQUIRE_OPERATOR_APPROVAL='true'; Write-Host 'Exact authorization: D-R3 TXT RESTORE'; Write-Host 'RESTORE method: bounded UPDATE to original accepted CREATE value'; Write-Host 'TXT DELETE authorized: false'; Write-Host 'MX/NS/general DNS changes authorized: false'; Write-Host ''
$ExitCode=1
try{$Output=& $Python 'scripts\dns_txt_pilot_live_restore.py' 2>&1; $ExitCode=$LASTEXITCODE; $Output|Tee-Object -FilePath $ResultFile|Out-Host}
finally{$env:WRITE_TOOLS_ENABLED='false';$env:DRY_RUN_DEFAULT='true';$env:D_R3_RESTORE_AUTHORIZATION_PHRASE='';$env:APPROVAL_SIGNING_SECRET=''}
Write-Host '';Write-Host '============================================================';Write-Host "LIVE_RESTORE_EXIT_CODE=$ExitCode";Write-Host 'WRITE_TOOLS_ENABLED=false';Write-Host 'TXT_DELETE_AUTHORIZED=false';Write-Host "LOCAL_RESULT_FILE=$ResultFile";Write-Host '============================================================'
if($ExitCode-ne 0){throw 'D-R3 TXT RESTORE did not complete cleanly. STOP. If provider_restore_returned=true, do not retry or delete without review.'}
